// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBBggVquwNpO_HJV4feN2H_zXuK6_5DtA',
    appId: '1:980479658075:web:4d410db536fe57e55e577e',
    messagingSenderId: '980479658075',
    projectId: 'adminpanelapp-ecommerce',
    authDomain: 'adminpanelapp-ecommerce.firebaseapp.com',
    storageBucket: 'adminpanelapp-ecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuReQW9r7Cp_R2yy2KK3AoFbtUPl1DRHQ',
    appId: '1:980479658075:android:2ce4a39989f83e7c5e577e',
    messagingSenderId: '980479658075',
    projectId: 'adminpanelapp-ecommerce',
    storageBucket: 'adminpanelapp-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPp8OO0VFiWC4Y4McZI_rYSAjQ11qBv8',
    appId: '1:980479658075:ios:08d6381b2474e3475e577e',
    messagingSenderId: '980479658075',
    projectId: 'adminpanelapp-ecommerce',
    storageBucket: 'adminpanelapp-ecommerce.appspot.com',
    iosBundleId: 'com.example.martApp',
  );
}
